using Ekiphan.Domain.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Ekiphan.Infrastructure.Persistence.Configurations;

internal sealed class TwoFactorRecoveryCodeConfiguration:IEntityTypeConfiguration<TwoFactorRecoveryCode>{public void Configure(EntityTypeBuilder<TwoFactorRecoveryCode>b){b.ToTable("TwoFactorRecoveryCodes");b.HasKey(x=>x.Id);b.Property(x=>x.CodeHash).HasMaxLength(128).IsUnicode(false);b.HasIndex(x=>x.AdminUserId);b.HasIndex(x=>x.CodeHash).IsUnique();b.HasIndex(x=>x.UsedAt);b.HasIndex(x=>x.RevokedAt);b.HasOne<AdminUser>().WithMany().HasForeignKey(x=>x.AdminUserId).OnDelete(DeleteBehavior.Cascade);}}
internal sealed class PasswordHistoryConfiguration:IEntityTypeConfiguration<PasswordHistory>{public void Configure(EntityTypeBuilder<PasswordHistory>b){b.ToTable("PasswordHistories");b.HasKey(x=>x.Id);b.Property(x=>x.PasswordHash).HasMaxLength(1000);b.HasIndex(x=>new{x.AdminUserId,x.CreatedAt});b.HasOne<AdminUser>().WithMany().HasForeignKey(x=>x.AdminUserId).OnDelete(DeleteBehavior.Cascade);}}
internal sealed class PasswordResetTokenConfiguration:IEntityTypeConfiguration<PasswordResetToken>{public void Configure(EntityTypeBuilder<PasswordResetToken>b){b.ToTable("PasswordResetTokens");b.HasKey(x=>x.Id);b.Property(x=>x.TokenHash).HasMaxLength(128).IsUnicode(false);b.Property(x=>x.RequestedIpAddress).HasMaxLength(64);b.Property(x=>x.RequestedUserAgent).HasMaxLength(1000);b.HasIndex(x=>x.AdminUserId);b.HasIndex(x=>x.TokenHash).IsUnique();b.HasIndex(x=>x.ExpiresAt);b.HasIndex(x=>x.UsedAt);}}
internal sealed class TemporarySecurityTokenConfiguration:IEntityTypeConfiguration<TemporarySecurityToken>{public void Configure(EntityTypeBuilder<TemporarySecurityToken>b){b.ToTable("TemporarySecurityTokens");b.HasKey(x=>x.Id);b.Property(x=>x.TokenHash).HasMaxLength(128).IsUnicode(false);b.Property(x=>x.Scope).HasMaxLength(200);b.HasIndex(x=>x.TokenHash).IsUnique();b.HasIndex(x=>new{x.AdminUserId,x.Purpose,x.ExpiresAt});}}
internal sealed class AdminLoginAttemptConfiguration:IEntityTypeConfiguration<AdminLoginAttempt>{public void Configure(EntityTypeBuilder<AdminLoginAttempt>b){b.ToTable("AdminLoginAttempts");b.HasKey(x=>x.Id);b.Property(x=>x.NormalizedEmail).HasMaxLength(254);b.Property(x=>x.IpAddress).HasMaxLength(64);b.Property(x=>x.UserAgent).HasMaxLength(1000);b.Property(x=>x.CorrelationId).HasMaxLength(100);b.HasIndex(x=>x.AdminUserId);b.HasIndex(x=>x.NormalizedEmail);b.HasIndex(x=>x.AttemptedAt);b.HasIndex(x=>x.WasSuccessful);b.HasIndex(x=>x.IpAddress);b.HasIndex(x=>x.FailureReason);}}
internal sealed class AuthorizationAuditLogConfiguration:IEntityTypeConfiguration<AuthorizationAuditLog>{public void Configure(EntityTypeBuilder<AuthorizationAuditLog>b){b.ToTable("AuthorizationAuditLogs");b.HasKey(x=>x.Id);b.Property(x=>x.Action).HasMaxLength(150);b.Property(x=>x.Category).HasMaxLength(100);b.Property(x=>x.EntityType).HasMaxLength(150);b.Property(x=>x.EntityId).HasMaxLength(100);b.Property(x=>x.Reason).HasMaxLength(1000);b.Property(x=>x.IpAddress).HasMaxLength(64);b.Property(x=>x.UserAgent).HasMaxLength(1000);b.Property(x=>x.CorrelationId).HasMaxLength(100);b.Property(x=>x.FailureCode).HasMaxLength(150);b.HasIndex(x=>x.ActorUserId);b.HasIndex(x=>x.TargetUserId);b.HasIndex(x=>x.Action);b.HasIndex(x=>x.Category);b.HasIndex(x=>new{x.EntityType,x.EntityId});b.HasIndex(x=>x.CreatedAt);b.HasIndex(x=>x.CorrelationId);}}
internal sealed class SecurityEventConfiguration:IEntityTypeConfiguration<SecurityEvent>{public void Configure(EntityTypeBuilder<SecurityEvent>b){b.ToTable("SecurityEvents");b.HasKey(x=>x.Id);b.Property(x=>x.Description).HasMaxLength(1000);b.Property(x=>x.IpAddress).HasMaxLength(64);b.Property(x=>x.UserAgent).HasMaxLength(1000);b.HasIndex(x=>x.AdminUserId);b.HasIndex(x=>x.EventType);b.HasIndex(x=>x.Severity);b.HasIndex(x=>x.CreatedAt);b.HasIndex(x=>x.IsReviewed);}}
internal sealed class SecurityNotificationOutboxConfiguration:IEntityTypeConfiguration<SecurityNotificationOutbox>{public void Configure(EntityTypeBuilder<SecurityNotificationOutbox>b){b.ToTable("SecurityNotificationOutbox");b.HasKey(x=>x.Id);b.Property(x=>x.Recipient).HasMaxLength(254);b.Property(x=>x.Type).HasMaxLength(100);b.Property(x=>x.ProtectedPayload).HasMaxLength(8000);b.Property(x=>x.LastError).HasMaxLength(1000);b.HasIndex(x=>new{x.ProcessedAt,x.CreatedAt});}}
