using Ekiphan.Domain.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Ekiphan.Infrastructure.Persistence.Configurations;
internal sealed class AdminRoleConfiguration:IEntityTypeConfiguration<AdminRole>{public void Configure(EntityTypeBuilder<AdminRole>b){b.ToTable("AdminRoles");b.HasKey(x=>x.Id);b.Property(x=>x.Name).HasMaxLength(100);b.Property(x=>x.NormalizedName).HasMaxLength(100);b.Property(x=>x.Description).HasMaxLength(500);b.Property(x=>x.RowVersion).IsRowVersion();b.HasIndex(x=>x.NormalizedName).IsUnique();b.HasIndex(x=>x.IsActive);b.HasMany(x=>x.Permissions).WithOne().HasForeignKey(x=>x.RoleId).OnDelete(DeleteBehavior.Cascade);b.Navigation(x=>x.Permissions).UsePropertyAccessMode(PropertyAccessMode.Field);}}
internal sealed class AdminPermissionConfiguration:IEntityTypeConfiguration<PermissionDefinition>{public void Configure(EntityTypeBuilder<PermissionDefinition>b){b.ToTable("AdminPermissions");b.HasKey(x=>x.Id);b.Property(x=>x.Code).HasMaxLength(150).IsUnicode(false);b.Property(x=>x.Name).HasMaxLength(200);b.Property(x=>x.Description).HasMaxLength(500);b.Property(x=>x.Group).HasMaxLength(100);b.HasIndex(x=>x.Code).IsUnique();b.HasIndex(x=>x.IsActive);}}
internal sealed class AdminUserRoleConfiguration:IEntityTypeConfiguration<AdminUserRole>{public void Configure(EntityTypeBuilder<AdminUserRole>b){b.ToTable("AdminUserRoles");b.HasKey(x=>new{x.AdminUserId,x.RoleId});b.HasOne<AdminUser>().WithMany().HasForeignKey(x=>x.AdminUserId).OnDelete(DeleteBehavior.Cascade);b.HasOne<AdminRole>().WithMany().HasForeignKey(x=>x.RoleId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class AdminRolePermissionConfiguration:IEntityTypeConfiguration<RolePermissionGrant>{public void Configure(EntityTypeBuilder<RolePermissionGrant>b){b.ToTable("AdminRolePermissions");b.HasKey(x=>new{x.RoleId,x.PermissionId});b.HasOne<PermissionDefinition>().WithMany().HasForeignKey(x=>x.PermissionId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class AdminUserPermissionOverrideConfiguration:IEntityTypeConfiguration<AdminUserPermissionOverride>{public void Configure(EntityTypeBuilder<AdminUserPermissionOverride>b){b.ToTable("AdminUserPermissionOverrides");b.HasKey(x=>x.Id);b.Property(x=>x.Reason).HasMaxLength(1000);b.HasIndex(x=>new{x.AdminUserId,x.PermissionId,x.OverrideType}).IsUnique();b.HasIndex(x=>x.ExpiresAt);b.HasOne<AdminUser>().WithMany().HasForeignKey(x=>x.AdminUserId).OnDelete(DeleteBehavior.Cascade);b.HasOne<PermissionDefinition>().WithMany().HasForeignKey(x=>x.PermissionId).OnDelete(DeleteBehavior.Restrict);}}
