using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Globalization;
using Ekiphan.Application.Identity;
using Ekiphan.Domain.Identity;
using Ekiphan.Infrastructure.Persistence;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Ekiphan.Infrastructure.Identity;

internal sealed class Sha256SecurityTokenHasher:ISecurityTokenHasher
{ public string Hash(string token)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token))); public string Generate(int bytes=32)=>Base64Url(RandomNumberGenerator.GetBytes(bytes)); private static string Base64Url(byte[] value)=>Convert.ToBase64String(value).TrimEnd('=').Replace('+','-').Replace('/','_'); }

internal sealed class TotpTwoFactorService(IDataProtectionProvider provider):ITwoFactorService
{
    private readonly IDataProtector protector=provider.CreateProtector("Ekiphan.Admin.TwoFactorSecret.v1");
    public string GenerateSecret()=>Base32.Encode(RandomNumberGenerator.GetBytes(20));
    public string Protect(string secret)=>protector.Protect(secret);
    public string Unprotect(string protectedSecret)=>protector.Unprotect(protectedSecret);
    public bool Verify(string secret,string code,int drift){if(code.Length!=6||!code.All(char.IsDigit))return false;var step=DateTimeOffset.UtcNow.ToUnixTimeSeconds()/30;for(var i=-Math.Abs(drift);i<=Math.Abs(drift);i++)if(FixedEquals(Code(secret,step+i),code))return true;return false;}
    public string BuildOtpAuthUri(string issuer,string account,string secret)=>$"otpauth://totp/{Uri.EscapeDataString(issuer)}:{Uri.EscapeDataString(account)}?secret={secret}&issuer={Uri.EscapeDataString(issuer)}&algorithm=SHA1&digits=6&period=30";
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Security","CA5350:Do Not Use Weak Cryptographic Algorithms",Justification="RFC 6238 interoperability requires HMAC-SHA1 for standard authenticator applications.")]
    private static string Code(string secret,long counter){Span<byte>b=stackalloc byte[8];System.Buffers.Binary.BinaryPrimitives.WriteInt64BigEndian(b,counter);using var h=new HMACSHA1(Base32.Decode(secret));var hash=h.ComputeHash(b.ToArray());var o=hash[^1]&15;var n=((hash[o]&127)<<24)|(hash[o+1]<<16)|(hash[o+2]<<8)|hash[o+3];return(n%1_000_000).ToString("D6",CultureInfo.InvariantCulture);}
    private static bool FixedEquals(string a,string b)=>CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(a),Encoding.ASCII.GetBytes(b));
    private static class Base32{private const string A="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";public static string Encode(byte[] d){var s=new StringBuilder();int buffer=0,bits=0;foreach(var x in d){buffer=(buffer<<8)|x;bits+=8;while(bits>=5){s.Append(A[(buffer>>(bits-5))&31]);bits-=5;}}if(bits>0)s.Append(A[(buffer<<(5-bits))&31]);return s.ToString();}public static byte[] Decode(string s){var bytes=new List<byte>();int buffer=0,bits=0;foreach(var c in s.TrimEnd('=').ToUpperInvariant()){var v=A.IndexOf(c);if(v<0)throw new FormatException("Invalid Base32 value.");buffer=(buffer<<5)|v;bits+=5;if(bits>=8){bytes.Add((byte)((buffer>>(bits-8))&255));bits-=8;}}return bytes.ToArray();}}
}

internal sealed class TwoFactorTokenService(EkiphanDbContext db,ISecurityTokenHasher hasher,TimeProvider clock):ITwoFactorTokenService
{ public async Task<string>CreateAsync(Guid userId,SecurityTokenPurpose purpose,string? scope,TimeSpan lifetime,CancellationToken ct){var now=clock.GetUtcNow();var old=await db.TemporarySecurityTokens.Where(x=>x.AdminUserId==userId&&x.Purpose==purpose&&x.UsedAt==null&&x.RevokedAt==null).ToListAsync(ct);foreach(var x in old)x.Revoke(now);var token=hasher.Generate();db.TemporarySecurityTokens.Add(new(Guid.NewGuid(),userId,hasher.Hash(token),purpose,scope,now.Add(lifetime)));await db.SaveChangesAsync(ct);return token;} public async Task<Guid?>ValidateAsync(string token,SecurityTokenPurpose purpose,string? scope,CancellationToken ct){var row=await Find(token,purpose,scope,ct);return row?.AdminUserId;}public async Task<Guid?>ConsumeAsync(string token,SecurityTokenPurpose purpose,string? scope,CancellationToken ct){var row=await Find(token,purpose,scope,ct);if(row is null)return null;row.Consume(clock.GetUtcNow());await db.SaveChangesAsync(ct);return row.AdminUserId;}private async Task<TemporarySecurityToken?>Find(string token,SecurityTokenPurpose purpose,string? scope,CancellationToken ct){var hash=hasher.Hash(token);var row=await db.TemporarySecurityTokens.SingleOrDefaultAsync(x=>x.TokenHash==hash&&x.Purpose==purpose,ct);return row is not null&&row.IsValid(clock.GetUtcNow())&&string.Equals(row.Scope,scope,StringComparison.Ordinal)?row:null;} }

internal sealed class SecureRecoveryCodeService(EkiphanDbContext db,ISecurityTokenHasher hasher,TimeProvider clock):IRecoveryCodeService
{ public async Task<IReadOnlyList<string>>RegenerateAsync(Guid userId,CancellationToken ct){await RevokeAsync(userId,ct);var values=Enumerable.Range(0,10).Select(_=>Format(hasher.Generate(8))).ToArray();foreach(var value in values)db.TwoFactorRecoveryCodes.Add(new(Guid.NewGuid(),userId,hasher.Hash(Normalize(value))));await db.SaveChangesAsync(ct);return values;}public async Task<bool>ConsumeAsync(Guid userId,string code,CancellationToken ct){var hash=hasher.Hash(Normalize(code));var row=await db.TwoFactorRecoveryCodes.SingleOrDefaultAsync(x=>x.AdminUserId==userId&&x.CodeHash==hash,ct);if(row is null||!row.IsUsable)return false;row.Use(clock.GetUtcNow());await db.SaveChangesAsync(ct);return true;}public async Task RevokeAsync(Guid userId,CancellationToken ct){var rows=await db.TwoFactorRecoveryCodes.Where(x=>x.AdminUserId==userId&&x.UsedAt==null&&x.RevokedAt==null).ToListAsync(ct);var now=clock.GetUtcNow();foreach(var row in rows)row.Revoke(now);await db.SaveChangesAsync(ct);}private static string Normalize(string x)=>x.Replace("-","").Trim().ToUpperInvariant();private static string Format(string x){var v=Normalize(x)[..12];return v[..4]+"-"+v[4..8]+"-"+v[8..12];}}

internal sealed class AuditValueSanitizer:IAuditValueSanitizer
{private static readonly string[] Sensitive=["password","token","secret","recoverycode","apikey","connectionstring","authorization"];public object? Sanitize(object? value){if(value is null)return null;using var doc=JsonDocument.Parse(JsonSerializer.Serialize(value));return Clean(doc.RootElement);}private static object? Clean(JsonElement e)=>e.ValueKind switch{JsonValueKind.Object=>e.EnumerateObject().ToDictionary(p=>p.Name,p=>Sensitive.Any(x=>p.Name.Contains(x,StringComparison.OrdinalIgnoreCase))?(object?)"[REDACTED]":Clean(p.Value)),JsonValueKind.Array=>e.EnumerateArray().Select(Clean).ToArray(),JsonValueKind.String=>e.GetString(),JsonValueKind.Number=>e.GetRawText(),JsonValueKind.True=>true,JsonValueKind.False=>false,_=>null};}

internal sealed class AuditLogService(EkiphanDbContext db,IAuditValueSanitizer sanitizer):IAuditLogService
{public async Task WriteAsync(Guid? actor,string action,string category,string entityType,string? entityId,Guid? target,object? oldValues,object? newValues,string? reason,AdminSecurityContext context,bool success,string? failure,CancellationToken ct){string? S(object? x)=>x is null?null:JsonSerializer.Serialize(sanitizer.Sanitize(x));db.AuthorizationAuditLogs.Add(new(Guid.NewGuid(),actor,action,category,entityType,entityId,target,S(oldValues),S(newValues),reason,context.IpAddress,context.UserAgent,context.CorrelationId,success,failure));await db.SaveChangesAsync(ct);}public async Task<IReadOnlyList<AuditLogListItemDto>>ListAsync(int page,int size,CancellationToken ct)=>await db.AuthorizationAuditLogs.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Skip((page-1)*size).Take(size).Select(x=>new AuditLogListItemDto(x.Id,x.ActorUserId,x.Action,x.Category,x.EntityType,x.EntityId,x.TargetUserId,x.Reason,Mask(x.IpAddress),x.CorrelationId,x.WasSuccessful,x.CreatedAt)).ToListAsync(ct);public async Task<AuditLogDetailDto?>GetAsync(Guid id,bool details,CancellationToken ct){var x=await db.AuthorizationAuditLogs.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);return x is null?null:new(new(x.Id,x.ActorUserId,x.Action,x.Category,x.EntityType,x.EntityId,x.TargetUserId,x.Reason,Mask(x.IpAddress),x.CorrelationId,x.WasSuccessful,x.CreatedAt),details?x.OldValues:null,details?x.NewValues:null,x.FailureCode,x.UserAgent);}private static string Mask(string? ip)=>string.IsNullOrWhiteSpace(ip)?"unknown":ip.Contains('.')?string.Join('.',ip.Split('.')[..3])+".*":"masked";}
