using Ekiphan.Application.Identity;
using Ekiphan.Domain.Identity;
using Ekiphan.Infrastructure.Persistence;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.DataProtection;

namespace Ekiphan.Infrastructure.Identity;

internal sealed class UserSecurityService(EkiphanDbContext db,ITwoFactorService totp,ITwoFactorTokenService tokens,IRecoveryCodeService recovery,IPasswordHasher<AdminUser> hasher,IOptions<AdminSecurityOptions> options,TimeProvider clock,IUserPermissionService permissionCache):IUserSecurityService
{
    private AdminSecurityOptions O=>options.Value;
    public async Task<SetupTwoFactorResultDto>SetupTwoFactorAsync(SetupTwoFactorCommand c,AdminSecurityContext context,CancellationToken ct){var user=await User(c.UserId,ct);if(user.IsTwoFactorEnabled)throw new InvalidOperationException("TWO_FACTOR_ALREADY_ENABLED");var secret=totp.GenerateSecret();user.BeginTwoFactorSetup(totp.Protect(secret));var token=await tokens.CreateAsync(user.Id,SecurityTokenPurpose.TwoFactorSetup,null,TimeSpan.FromMinutes(O.TwoFactorSetupTokenLifetimeMinutes),ct);await db.SaveChangesAsync(ct);var expiry=clock.GetUtcNow().AddMinutes(O.TwoFactorSetupTokenLifetimeMinutes);return new(token,totp.BuildOtpAuthUri("Ekiphan",user.Email,secret),secret,expiry,"Ekiphan",user.Email);}
    public async Task<ConfirmTwoFactorResultDto>ConfirmTwoFactorAsync(ConfirmTwoFactorCommand c,AdminSecurityContext context,CancellationToken ct){var tokenUser=await tokens.ValidateAsync(c.SetupToken,SecurityTokenPurpose.TwoFactorSetup,null,ct);if(tokenUser!=c.UserId)throw new InvalidOperationException("TWO_FACTOR_SETUP_NOT_FOUND");var user=await User(c.UserId,ct);if(string.IsNullOrWhiteSpace(user.TwoFactorSecretEncrypted)||!totp.Verify(totp.Unprotect(user.TwoFactorSecretEncrypted),c.TotpCode,O.TotpAllowedTimeStepDrift))throw new InvalidOperationException("TWO_FACTOR_CODE_INVALID");await using var tx=await db.Database.BeginTransactionAsync(ct);if(await tokens.ConsumeAsync(c.SetupToken,SecurityTokenPurpose.TwoFactorSetup,null,ct)!=user.Id)throw new InvalidOperationException("TWO_FACTOR_SETUP_NOT_FOUND");user.EnableTwoFactor(clock.GetUtcNow());var codes=await recovery.RegenerateAsync(user.Id,ct);RevokeOthers(user.Id,null,"Two-factor authentication enabled");await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);permissionCache.Invalidate(user.Id);return new(true,codes);}
    public async Task DisableTwoFactorAsync(DisableTwoFactorCommand c,AdminSecurityContext context,CancellationToken ct){var user=await User(c.UserId,ct);VerifyPassword(user,c.CurrentPassword);if(!user.IsTwoFactorEnabled)throw new InvalidOperationException("TWO_FACTOR_NOT_ENABLED");var ok=totp.Verify(totp.Unprotect(user.TwoFactorSecretEncrypted!),c.Code,O.TotpAllowedTimeStepDrift)||await recovery.ConsumeAsync(user.Id,c.Code,ct);if(!ok)throw new InvalidOperationException("TWO_FACTOR_CODE_INVALID");await using var tx=await db.Database.BeginTransactionAsync(ct);await recovery.RevokeAsync(user.Id,ct);user.DisableTwoFactor(clock.GetUtcNow());RevokeOthers(user.Id,context.SessionId,"Two-factor authentication disabled");await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);permissionCache.Invalidate(user.Id);}
    public async Task<IReadOnlyList<string>>RegenerateRecoveryCodesAsync(RegenerateRecoveryCodesCommand c,AdminSecurityContext context,CancellationToken ct){var user=await User(c.UserId,ct);VerifyPassword(user,c.CurrentPassword);if(!user.IsTwoFactorEnabled||!totp.Verify(totp.Unprotect(user.TwoFactorSecretEncrypted!),c.TotpCode,O.TotpAllowedTimeStepDrift))throw new InvalidOperationException("TWO_FACTOR_CODE_INVALID");return await recovery.RegenerateAsync(user.Id,ct);}
    public async Task<TwoFactorChallengeDto>CreateLoginChallengeAsync(Guid userId,CancellationToken ct){var user=await User(userId,ct);if(!user.IsTwoFactorEnabled)throw new InvalidOperationException("TWO_FACTOR_NOT_ENABLED");var token=await tokens.CreateAsync(userId,SecurityTokenPurpose.TwoFactorLogin,null,TimeSpan.FromMinutes(O.TwoFactorLoginTokenLifetimeMinutes),ct);return new(token,clock.GetUtcNow().AddMinutes(O.TwoFactorLoginTokenLifetimeMinutes),["Totp","RecoveryCode"]);}
    public async Task<VerifyTwoFactorResultDto>VerifyLoginAsync(VerifyTwoFactorLoginCommand c,AdminSecurityContext context,CancellationToken ct){var userId=await tokens.ValidateAsync(c.TwoFactorToken,SecurityTokenPurpose.TwoFactorLogin,null,ct)??throw new InvalidOperationException("LOGIN_TOKEN_INVALID");var user=await User(userId,ct);var now=clock.GetUtcNow();if(user.IsTwoFactorLocked(now))throw new InvalidOperationException("TWO_FACTOR_LOCKED");var ok=c.Method=="Totp"?totp.Verify(totp.Unprotect(user.TwoFactorSecretEncrypted!),c.Code,O.TotpAllowedTimeStepDrift):await recovery.ConsumeAsync(user.Id,c.Code,ct);if(!ok){user.RegisterTwoFactorFailure(now,O.TwoFactorMaxAttempts,TimeSpan.FromMinutes(O.TwoFactorLockoutMinutes));await db.SaveChangesAsync(ct);throw new InvalidOperationException("TWO_FACTOR_CODE_INVALID");}if(await tokens.ConsumeAsync(c.TwoFactorToken,SecurityTokenPurpose.TwoFactorLogin,null,ct)!=user.Id)throw new InvalidOperationException("LOGIN_TOKEN_ALREADY_USED");user.RegisterTwoFactorSuccess(now);await db.SaveChangesAsync(ct);var permissions=await permissionCache.GetEffectivePermissionsAsync(user.Id,ct);return new(new(user.Id,user.Email,user.DisplayName,permissions.Order().ToArray(),user.SecurityStamp,true,user.AuthorizationVersion));}
    private async Task<AdminUser>User(Guid id,CancellationToken ct)=>await db.AdminUsers.SingleOrDefaultAsync(x=>x.Id==id&&x.IsActive,ct)??throw new KeyNotFoundException("USER_NOT_FOUND");
    private void VerifyPassword(AdminUser user,string password){if(hasher.VerifyHashedPassword(user,user.PasswordHash,password)==PasswordVerificationResult.Failed)throw new InvalidOperationException("PASSWORD_CURRENT_INVALID");}
    private void RevokeOthers(Guid userId,Guid? keep,string reason){var now=clock.GetUtcNow();foreach(var s in db.AdminSessions.Where(x=>x.AdminUserId==userId&&x.Id!=keep&&x.RevokedAt==null))s.Revoke(now,userId,reason);}
}

internal sealed class AdminSessionService(EkiphanDbContext db,TimeProvider clock):IAdminSessionService
{public async Task<IReadOnlyList<AdminSessionDto>>GetAsync(Guid userId,Guid current,CancellationToken ct){var now=clock.GetUtcNow();var rows=await db.AdminSessions.AsNoTracking().Where(x=>x.AdminUserId==userId).OrderByDescending(x=>x.LastActivityAt).ToListAsync(ct);return rows.Select(x=>new AdminSessionDto(x.Id,x.DeviceName??"Unknown device",x.Browser,x.OperatingSystem,Mask(x.IpAddress),x.CreatedAt,x.LastActivityAt,x.ExpiresAt,x.Id==current,x.RevokedAt.HasValue?"Revoked":x.ExpiresAt<=now?"Expired":"Active")).ToArray();}public async Task<bool>RevokeAsync(Guid actor,Guid sessionId,bool canOthers,string reason,CancellationToken ct){var row=await db.AdminSessions.SingleOrDefaultAsync(x=>x.Id==sessionId,ct);if(row is null)return false;if(row.AdminUserId!=actor&&!canOthers)throw new UnauthorizedAccessException("SESSION_NOT_OWNED_BY_USER");if(row.RevokedAt.HasValue)throw new InvalidOperationException("SESSION_ALREADY_REVOKED");row.Revoke(clock.GetUtcNow(),actor,reason);await db.SaveChangesAsync(ct);return true;}public async Task<int>RevokeOthersAsync(Guid userId,Guid current,string reason,CancellationToken ct)=>await RevokeWhere(db.AdminSessions.Where(x=>x.AdminUserId==userId&&x.Id!=current&&x.RevokedAt==null),userId,reason,ct);public async Task<int>RevokeUserAsync(Guid actor,Guid userId,string reason,CancellationToken ct)=>await RevokeWhere(db.AdminSessions.Where(x=>x.AdminUserId==userId&&x.RevokedAt==null),actor,reason,ct);private async Task<int>RevokeWhere(IQueryable<AdminSession>q,Guid actor,string reason,CancellationToken ct){var rows=await q.ToListAsync(ct);var now=clock.GetUtcNow();foreach(var x in rows)x.Revoke(now,actor,reason);await db.SaveChangesAsync(ct);return rows.Count;}private static string Mask(string? ip)=>string.IsNullOrEmpty(ip)?"unknown":ip.Contains('.')?string.Join('.',ip.Split('.')[..3])+".*":"masked";}

internal sealed class LoginAttemptService(EkiphanDbContext db,TimeProvider clock):ILoginAttemptService
{public async Task RecordAsync(Guid? userId,string email,bool success,LoginFailureReason reason,AdminSecurityContext context,bool twoFactor,CancellationToken ct){db.AdminLoginAttempts.Add(new(Guid.NewGuid(),userId,email,clock.GetUtcNow(),success,reason,context.IpAddress,context.UserAgent,context.CorrelationId,twoFactor));await db.SaveChangesAsync(ct);}public async Task<IReadOnlyList<LoginAttemptDto>>GetUserHistoryAsync(Guid userId,int page,int size,CancellationToken ct)=>await db.AdminLoginAttempts.AsNoTracking().Where(x=>x.AdminUserId==userId).OrderByDescending(x=>x.AttemptedAt).Skip((page-1)*size).Take(size).Select(x=>new LoginAttemptDto(x.Id,x.AttemptedAt,x.WasSuccessful,x.FailureReason.ToString(),"masked",x.Browser,x.RiskLevel.ToString())).ToListAsync(ct);}

internal sealed class PasswordSecurityService(EkiphanDbContext db,IPasswordHasher<AdminUser> hasher,ITwoFactorService totp,IOptions<AdminSecurityOptions> options,TimeProvider clock,IUserPermissionService cache):IPasswordSecurityService
{public async Task ChangeAsync(ChangePasswordCommand c,AdminSecurityContext context,CancellationToken ct){var user=await db.AdminUsers.SingleOrDefaultAsync(x=>x.Id==c.UserId&&x.IsActive,ct)??throw new KeyNotFoundException("USER_NOT_FOUND");if(hasher.VerifyHashedPassword(user,user.PasswordHash,c.CurrentPassword)==PasswordVerificationResult.Failed)throw new InvalidOperationException("PASSWORD_CURRENT_INVALID");AdminPasswordPolicy.EnsureStrong(c.NewPassword);if(hasher.VerifyHashedPassword(user,user.PasswordHash,c.NewPassword)!=PasswordVerificationResult.Failed)throw new InvalidOperationException("PASSWORD_REUSED");var history=await db.PasswordHistories.Where(x=>x.AdminUserId==user.Id).OrderByDescending(x=>x.CreatedAt).Take(options.Value.PasswordHistoryCount).ToListAsync(ct);if(history.Any(x=>hasher.VerifyHashedPassword(user,x.PasswordHash,c.NewPassword)!=PasswordVerificationResult.Failed))throw new InvalidOperationException("PASSWORD_REUSED");if(user.IsTwoFactorEnabled&&(string.IsNullOrWhiteSpace(c.TotpCode)||!totp.Verify(totp.Unprotect(user.TwoFactorSecretEncrypted!),c.TotpCode,options.Value.TotpAllowedTimeStepDrift)))throw new InvalidOperationException("TWO_FACTOR_CODE_INVALID");await using var tx=await db.Database.BeginTransactionAsync(ct);db.PasswordHistories.Add(new(Guid.NewGuid(),user.Id,user.PasswordHash));user.SetPasswordHash(hasher.HashPassword(user,c.NewPassword));user.PermissionsChanged(clock.GetUtcNow());var sessions=await db.AdminSessions.Where(x=>x.AdminUserId==user.Id&&x.Id!=c.CurrentSessionId&&x.RevokedAt==null).ToListAsync(ct);foreach(var x in sessions)x.Revoke(clock.GetUtcNow(),user.Id,"Password changed");await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);cache.Invalidate(user.Id);}}

internal sealed class ReAuthenticationService(EkiphanDbContext db,IPasswordHasher<AdminUser> hasher,ITwoFactorService totp,ITwoFactorTokenService tokens,IOptions<AdminSecurityOptions> options):IReAuthenticationService
{public async Task<ReAuthenticationResultDto>ReAuthenticateAsync(ReAuthenticateCommand c,CancellationToken ct){var user=await db.AdminUsers.SingleOrDefaultAsync(x=>x.Id==c.UserId&&x.IsActive,ct)??throw new KeyNotFoundException("USER_NOT_FOUND");if(hasher.VerifyHashedPassword(user,user.PasswordHash,c.Password)==PasswordVerificationResult.Failed)throw new InvalidOperationException("INVALID_CREDENTIALS");if(user.IsTwoFactorEnabled&&(string.IsNullOrWhiteSpace(c.TotpCode)||!totp.Verify(totp.Unprotect(user.TwoFactorSecretEncrypted!),c.TotpCode,options.Value.TotpAllowedTimeStepDrift)))throw new InvalidOperationException("TWO_FACTOR_CODE_INVALID");var lifetime=TimeSpan.FromMinutes(options.Value.ReAuthenticationTokenLifetimeMinutes);var token=await tokens.CreateAsync(user.Id,SecurityTokenPurpose.ReAuthentication,c.Scope,lifetime,ct);return new(token,DateTimeOffset.UtcNow.Add(lifetime),c.Scope);}public async Task<bool>ConsumeAsync(string token,Guid userId,string scope,CancellationToken ct)=>(await tokens.ConsumeAsync(token,SecurityTokenPurpose.ReAuthentication,scope,ct))==userId;}

internal sealed class DefaultSecurityRiskEvaluator:ISecurityRiskEvaluator{public SecurityRiskLevel Evaluate(int failures,bool newIp,bool newDevice)=>failures>=5?SecurityRiskLevel.High:failures>=3||newIp&&newDevice?SecurityRiskLevel.Medium:newIp||newDevice?SecurityRiskLevel.Low:SecurityRiskLevel.Information;}

internal sealed class SecurityEventService(EkiphanDbContext db,TimeProvider clock):ISecurityEventService
{public async Task<IReadOnlyList<SecurityEventDto>>ListAsync(int page,int size,CancellationToken ct)=>await db.SecurityEvents.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Skip((page-1)*size).Take(size).Select(x=>new SecurityEventDto(x.Id,x.AdminUserId,x.EventType.ToString(),x.Severity.ToString(),x.Description,x.IsReviewed,x.CreatedAt)).ToListAsync(ct);public async Task<bool>ReviewAsync(Guid id,Guid actor,CancellationToken ct){var row=await db.SecurityEvents.SingleOrDefaultAsync(x=>x.Id==id,ct);if(row is null)return false;row.Review(actor,clock.GetUtcNow());await db.SaveChangesAsync(ct);return true;}public async Task<SecurityDashboardDto>DashboardAsync(CancellationToken ct){var since=clock.GetUtcNow().AddHours(-24);var high=await db.SecurityEvents.AsNoTracking().Where(x=>x.CreatedAt>=since&&x.Severity>=SecurityRiskLevel.High).OrderByDescending(x=>x.CreatedAt).Take(10).Select(x=>new SecurityEventDto(x.Id,x.AdminUserId,x.EventType.ToString(),x.Severity.ToString(),x.Description,x.IsReviewed,x.CreatedAt)).ToListAsync(ct);return new(await db.AdminLoginAttempts.CountAsync(x=>x.AttemptedAt>=since&&x.WasSuccessful,ct),await db.AdminLoginAttempts.CountAsync(x=>x.AttemptedAt>=since&&!x.WasSuccessful,ct),await db.AdminUsers.CountAsync(x=>x.LockoutEnd>clock.GetUtcNow(),ct),await db.AdminSessions.CountAsync(x=>x.RevokedAt==null&&x.ExpiresAt>clock.GetUtcNow(),ct),await db.AdminUsers.CountAsync(x=>x.IsActive&&!x.IsTwoFactorEnabled,ct),high,await db.AdminSessions.CountAsync(x=>x.RevokedAt>=since,ct),await db.SecurityEvents.CountAsync(x=>x.EventType==SecurityEventType.PasswordResetRequested&&x.CreatedAt>=since,ct),await db.SecurityEvents.CountAsync(x=>x.Severity==SecurityRiskLevel.Critical&&x.CreatedAt>=since,ct));}}

internal sealed class SecurityNotificationService(EkiphanDbContext db,IDataProtectionProvider provider):ISecurityNotificationService
{private readonly IDataProtector protector=provider.CreateProtector("Ekiphan.Admin.SecurityNotification.v1");public Task QueuePasswordResetAsync(string email,string token,CancellationToken ct)=>Queue(email,"PasswordReset",token,ct);public Task QueuePasswordChangedAsync(string email,CancellationToken ct)=>Queue(email,"PasswordChanged",string.Empty,ct);private async Task Queue(string email,string type,string value,CancellationToken ct){db.SecurityNotificationOutbox.Add(new(Guid.NewGuid(),email,type,protector.Protect(value)));await db.SaveChangesAsync(ct);}}

internal sealed class PasswordResetService(EkiphanDbContext db,ISecurityTokenHasher tokenHasher,IPasswordHasher<AdminUser> passwordHasher,ISecurityNotificationService notifications,IOptions<AdminSecurityOptions> options,TimeProvider clock,IUserPermissionService cache):IPasswordResetService
{public async Task RequestAsync(ForgotPasswordCommand c,AdminSecurityContext context,CancellationToken ct){var normalized=c.Email.Trim().ToUpperInvariant();var user=await db.AdminUsers.SingleOrDefaultAsync(x=>x.NormalizedEmail==normalized&&x.IsActive,ct);if(user is null)return;var now=clock.GetUtcNow();var old=await db.PasswordResetTokens.Where(x=>x.AdminUserId==user.Id&&x.UsedAt==null&&x.RevokedAt==null).ToListAsync(ct);foreach(var x in old)x.Revoke(now);var token=tokenHasher.Generate();db.PasswordResetTokens.Add(new(Guid.NewGuid(),user.Id,tokenHasher.Hash(token),now.AddMinutes(options.Value.PasswordResetTokenLifetimeMinutes),context.IpAddress,context.UserAgent));db.SecurityEvents.Add(new(Guid.NewGuid(),user.Id,SecurityEventType.PasswordResetRequested,SecurityRiskLevel.Information,"Password reset requested",context.IpAddress,context.UserAgent,null,null));await db.SaveChangesAsync(ct);await notifications.QueuePasswordResetAsync(user.Email,token,ct);}public async Task ResetAsync(ResetPasswordCommand c,AdminSecurityContext context,CancellationToken ct){AdminPasswordPolicy.EnsureStrong(c.NewPassword);var hash=tokenHasher.Hash(c.Token);var row=await db.PasswordResetTokens.SingleOrDefaultAsync(x=>x.TokenHash==hash,ct)??throw new InvalidOperationException("PASSWORD_RESET_TOKEN_INVALID");var now=clock.GetUtcNow();if(!row.IsValid(now))throw new InvalidOperationException(row.ExpiresAt<=now?"PASSWORD_RESET_TOKEN_EXPIRED":"PASSWORD_RESET_TOKEN_USED");var user=await db.AdminUsers.SingleAsync(x=>x.Id==row.AdminUserId,ct);var history=await db.PasswordHistories.Where(x=>x.AdminUserId==user.Id).OrderByDescending(x=>x.CreatedAt).Take(options.Value.PasswordHistoryCount).ToListAsync(ct);if(history.Any(x=>passwordHasher.VerifyHashedPassword(user,x.PasswordHash,c.NewPassword)!=PasswordVerificationResult.Failed))throw new InvalidOperationException("PASSWORD_REUSED");await using var tx=await db.Database.BeginTransactionAsync(ct);db.PasswordHistories.Add(new(Guid.NewGuid(),user.Id,user.PasswordHash));user.SetPasswordHash(passwordHasher.HashPassword(user,c.NewPassword));user.PermissionsChanged(now);row.Use(now);var sessions=await db.AdminSessions.Where(x=>x.AdminUserId==user.Id&&x.RevokedAt==null).ToListAsync(ct);foreach(var x in sessions)x.Revoke(now,user.Id,"Password reset");db.SecurityEvents.Add(new(Guid.NewGuid(),user.Id,SecurityEventType.PasswordChanged,SecurityRiskLevel.Information,"Password reset completed",context.IpAddress,context.UserAgent,null,null));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);cache.Invalidate(user.Id);await notifications.QueuePasswordChangedAsync(user.Email,ct);}}
