import type { Metadata } from "next";
import Image from "next/image";
import { PublicHeader } from "../../../components/public-header";
import styles from "../../referanslar/references.module.css";

export const metadata: Metadata = { title: "References | Ekiphan", description: "Brands and partners we work with on professional kitchen projects.", alternates: { canonical: "/en/references", languages: { tr: "/referanslar", en: "/en/references" } } };
const references: { name: string; sub?: string; accent: string }[] = [{ name: "arcelik", accent: "red" }, { name: "VESTEL", accent: "red" }, { name: "divan", accent: "dark" }, { name: "RAMADA", sub: "BY WYNDHAM", accent: "burgundy" }, { name: "MEDA", sub: "TOWER", accent: "gray" }, { name: "MEDICANA", accent: "teal" }, { name: "DOĞUŞ", sub: "GRUBU", accent: "blue" }, { name: "TAHA", sub: "KARGO", accent: "blue" }, { name: "EGE", sub: "YAPI", accent: "gold" }, { name: "Radisson", accent: "blue" }, { name: "POLIMEKS", accent: "gray" }, { name: "ATASAY", accent: "gold" }, { name: "FERKO", accent: "teal" }, { name: "akasya", accent: "orange" }, { name: "İSKELE", sub: "YAPI", accent: "gray" }];

export default function EnglishReferencesPage() {
  return <main className={styles.page} data-public-page><PublicHeader currentPath="/en/references" />
    <section className={styles.hero} aria-labelledby="references-title"><div className={styles.heroCopy}><div className={styles.eyebrow}><span>01</span><i aria-hidden="true" /><strong>OUR PARTNERS</strong></div><h1 id="references-title">Our references<em>built together.</em></h1><p className={styles.heroLead}>We work alongside leading brands in Türkiye and around the world on professional kitchen projects.</p><div className={styles.heroMeta}><span className={styles.heroMetaNumber}>15</span><span className={styles.heroMetaLabel}>PARTNERS</span></div></div><div className={styles.heroVisual}><Image src="/images/ekiphan-kitchen-hero.png" alt="Professional kitchen project" fill priority sizes="(max-width: 900px) 100vw, 55vw" /><div className={styles.heroVisualShade} aria-hidden="true" /><span className={styles.heroVisualLabel}>EKIPHAN / REFERENCES</span></div></section>
    <section className={styles.brandSection} aria-labelledby="partners-title"><div className={styles.brandTopline}><div className={styles.brandEyebrow}><span>02</span><span>TRUSTED BRANDS</span></div><div className={styles.partnerCount}><strong>15+</strong><span>PARTNERS</span></div></div><div className={styles.sectionIntro}><div><h2 id="partners-title">Strong partnerships,<em>solid projects.</em></h2></div><p>We bring together the brands that help us deliver projects across a range of sectors.</p></div>
      <div className={styles.filters} aria-label="Reference categories"><button type="button" className={styles.filterActive}>All</button><button type="button">Hotels</button><button type="button">Restaurants</button><button type="button">Industrial Kitchens</button><button type="button">Cafés</button><button type="button">Public / Corporate</button><button type="button">International Projects</button></div>
      <div className={styles.brandGrid}>{references.map((brand,index)=><article className={`${styles.brandCard} ${styles[`brand_${brand.accent}`]}`} key={brand.name}><span className={styles.brandNumber}>{String(index+1).padStart(2,"0")}</span><div className={styles.brandMark}><span>{brand.name}</span>{brand.sub ? <small>{brand.sub}</small> : null}</div></article>)}</div>
    </section><section className={styles.statement}><span>03</span><p>For every project, we plan the right brand, equipment and implementation together.</p></section>
  </main>;
}
