using Ekiphan.Domain.Common;

namespace Ekiphan.Domain.Identity;

public enum TwoFactorStatus { Disabled=0,SetupPending=1,Enabled=2,RecoveryRequired=3,Locked=4 }
public enum SecurityTokenPurpose { TwoFactorSetup=1,TwoFactorLogin=2,ReAuthentication=3 }
public enum LoginFailureReason { None=0,InvalidCredentials=1,UserNotFound=2,UserInactive=3,AccountLocked=4,TwoFactorRequired=5,InvalidTwoFactorCode=6,RecoveryCodeInvalid=7,TwoFactorLocked=8,SessionRejected=9,SecurityStampMismatch=10,Unknown=99 }
public enum SecurityRiskLevel { Information=0,Low=1,Medium=2,High=3,Critical=4 }
public enum SecurityEventType { MultipleFailedLogins=1,MultipleFailedTwoFactorAttempts=2,LoginFromNewDevice=3,LoginFromNewIp=4,SessionTokenReuse=5,PasswordResetRequested=6,PasswordChanged=7,TwoFactorDisabled=8,AccountLocked=9,PermissionEscalation=10,SuspiciousSessionActivity=11 }

public sealed class TwoFactorRecoveryCode:Entity
{ private TwoFactorRecoveryCode(){} public TwoFactorRecoveryCode(Guid id,Guid userId,string hash):base(id){AdminUserId=userId;CodeHash=hash;} public Guid AdminUserId{get;private set;} public string CodeHash{get;private set;}=""; public DateTimeOffset? UsedAt{get;private set;} public DateTimeOffset? RevokedAt{get;private set;} public bool IsUsable=>UsedAt is null&&RevokedAt is null; public void Use(DateTimeOffset now){if(!IsUsable)throw new InvalidOperationException("RECOVERY_CODE_ALREADY_USED");UsedAt=now;} public void Revoke(DateTimeOffset now)=>RevokedAt??=now; }
public sealed class PasswordHistory:Entity
{ private PasswordHistory(){} public PasswordHistory(Guid id,Guid userId,string hash):base(id){AdminUserId=userId;PasswordHash=hash;} public Guid AdminUserId{get;private set;} public string PasswordHash{get;private set;}=""; }
public sealed class PasswordResetToken:Entity
{ private PasswordResetToken(){} public PasswordResetToken(Guid id,Guid userId,string hash,DateTimeOffset expiresAt,string? ip,string? agent):base(id){AdminUserId=userId;TokenHash=hash;ExpiresAt=expiresAt;RequestedIpAddress=ip;RequestedUserAgent=agent;} public Guid AdminUserId{get;private set;} public string TokenHash{get;private set;}=""; public DateTimeOffset ExpiresAt{get;private set;} public DateTimeOffset? UsedAt{get;private set;} public DateTimeOffset? RevokedAt{get;private set;} public string? RequestedIpAddress{get;private set;} public string? RequestedUserAgent{get;private set;} public bool IsValid(DateTimeOffset now)=>UsedAt is null&&RevokedAt is null&&ExpiresAt>now; public void Use(DateTimeOffset now){if(!IsValid(now))throw new InvalidOperationException("PASSWORD_RESET_TOKEN_INVALID");UsedAt=now;} public void Revoke(DateTimeOffset now)=>RevokedAt??=now; }
public sealed class TemporarySecurityToken:Entity
{ private TemporarySecurityToken(){} public TemporarySecurityToken(Guid id,Guid userId,string hash,SecurityTokenPurpose purpose,string? scope,DateTimeOffset expiresAt):base(id){AdminUserId=userId;TokenHash=hash;Purpose=purpose;Scope=scope;ExpiresAt=expiresAt;} public Guid AdminUserId{get;private set;} public string TokenHash{get;private set;}=""; public SecurityTokenPurpose Purpose{get;private set;} public string? Scope{get;private set;} public DateTimeOffset ExpiresAt{get;private set;} public DateTimeOffset? UsedAt{get;private set;} public DateTimeOffset? RevokedAt{get;private set;} public bool IsValid(DateTimeOffset now)=>UsedAt is null&&RevokedAt is null&&ExpiresAt>now; public void Consume(DateTimeOffset now){if(!IsValid(now))throw new InvalidOperationException("SECURITY_TOKEN_INVALID");UsedAt=now;} public void Revoke(DateTimeOffset now)=>RevokedAt??=now; }
public sealed class AdminLoginAttempt:Entity
{ private AdminLoginAttempt(){} public AdminLoginAttempt(Guid id,Guid? userId,string email,DateTimeOffset at,bool success,LoginFailureReason reason,string? ip,string? agent,string correlationId,bool twoFactorRequired=false):base(id){AdminUserId=userId;NormalizedEmail=email;AttemptedAt=at;WasSuccessful=success;FailureReason=reason;IpAddress=ip;UserAgent=agent;CorrelationId=correlationId;TwoFactorRequired=twoFactorRequired;} public Guid? AdminUserId{get;private set;} public string NormalizedEmail{get;private set;}=""; public DateTimeOffset AttemptedAt{get;private set;} public bool WasSuccessful{get;private set;} public LoginFailureReason FailureReason{get;private set;} public string? IpAddress{get;private set;} public string? UserAgent{get;private set;} public string? Browser{get;private set;} public string? OperatingSystem{get;private set;} public string? DeviceId{get;private set;} public Guid? SessionId{get;private set;} public string CorrelationId{get;private set;}=""; public bool TwoFactorRequired{get;private set;} public string? TwoFactorMethod{get;private set;} public bool? TwoFactorSucceeded{get;private set;} public SecurityRiskLevel RiskLevel{get;private set;} }
public sealed class AuthorizationAuditLog:Entity
{ private AuthorizationAuditLog(){} public AuthorizationAuditLog(Guid id,Guid? actor,string action,string category,string entityType,string? entityId,Guid? target,string? oldValues,string? newValues,string? reason,string? ip,string? agent,string correlationId,bool success,string? failure):base(id){ActorUserId=actor;Action=action;Category=category;EntityType=entityType;EntityId=entityId;TargetUserId=target;OldValues=oldValues;NewValues=newValues;Reason=reason;IpAddress=ip;UserAgent=agent;CorrelationId=correlationId;WasSuccessful=success;FailureCode=failure;} public Guid? ActorUserId{get;private set;} public Guid? ActorSessionId{get;private set;} public string Action{get;private set;}=""; public string Category{get;private set;}=""; public string EntityType{get;private set;}=""; public string? EntityId{get;private set;} public Guid? TargetUserId{get;private set;} public string? OldValues{get;private set;} public string? NewValues{get;private set;} public string? Reason{get;private set;} public string? IpAddress{get;private set;} public string? UserAgent{get;private set;} public string CorrelationId{get;private set;}=""; public bool WasSuccessful{get;private set;} public string? FailureCode{get;private set;} }
public sealed class SecurityEvent:Entity
{ private SecurityEvent(){} public SecurityEvent(Guid id,Guid? userId,SecurityEventType type,SecurityRiskLevel severity,string description,string? ip,string? agent,Guid? sessionId,string? metadata):base(id){AdminUserId=userId;EventType=type;Severity=severity;Description=description;IpAddress=ip;UserAgent=agent;SessionId=sessionId;Metadata=metadata;} public Guid? AdminUserId{get;private set;} public SecurityEventType EventType{get;private set;} public SecurityRiskLevel Severity{get;private set;} public string? IpAddress{get;private set;} public string? UserAgent{get;private set;} public Guid? SessionId{get;private set;} public string Description{get;private set;}=""; public string? Metadata{get;private set;} public bool IsReviewed{get;private set;} public DateTimeOffset? ReviewedAt{get;private set;} public Guid? ReviewedByUserId{get;private set;} public void Review(Guid actor,DateTimeOffset now){IsReviewed=true;ReviewedAt=now;ReviewedByUserId=actor;} }
public sealed class SecurityNotificationOutbox:Entity
{private SecurityNotificationOutbox(){}public SecurityNotificationOutbox(Guid id,string recipient,string type,string protectedPayload):base(id){Recipient=recipient;Type=type;ProtectedPayload=protectedPayload;}public string Recipient{get;private set;}="";public string Type{get;private set;}="";public string ProtectedPayload{get;private set;}="";public DateTimeOffset? ProcessedAt{get;private set;}public int AttemptCount{get;private set;}public string? LastError{get;private set;}public void Complete(DateTimeOffset now)=>ProcessedAt=now;public void Fail(string error){AttemptCount++;LastError=error[..Math.Min(error.Length,1000)];}}
